"""Media provenance and AI-generation hints.

Checks (1) presence of a C2PA/JUMBF manifest, (2) generator strings left in
metadata, and (3) runs any plugged-in classifiers. Absence of a C2PA manifest is
NOT evidence of fakery; presence of a valid, signed one is evidence of origin
(signature validation requires the c2patool / c2pa library, see verify_c2pa).
"""
import shutil
import subprocess
from . import Finding

GENERATORS = [b"stable diffusion", b"midjourney", b"dall-e", b"dall\xc2\xb7e", b"firefly",
              b"comfyui", b"automatic1111", b"sora", b"runway", b"synthid", b"generated by ai"]
CLASSIFIERS = []  # callables: bytes -> (score 0..1, name); register calibrated models here


def register_classifier(fn):
    CLASSIFIERS.append(fn)


def verify_c2pa(path):
    """Use c2patool if installed for real signature validation."""
    exe = shutil.which("c2patool")
    if not exe:
        return None
    r = subprocess.run([exe, path], capture_output=True, text=True, timeout=60)
    return r.returncode == 0, r.stdout[:2000]


def analyze_media(path):
    data = open(path, "rb").read()
    low = data.lower()
    out = []
    has_c2pa = b"c2pa" in low and b"jumb" in low
    if has_c2pa:
        v = verify_c2pa(path)
        if v is None:
            out.append(Finding("media.c2pa_present", "low", "C2PA manifest present; signature NOT validated (c2patool missing)", {}))
        elif v[0]:
            out.append(Finding("media.c2pa_valid", "low", "C2PA manifest validated", {"report": v[1]}))
        else:
            out.append(Finding("media.c2pa_invalid", "high", "C2PA manifest present but failed validation (possible tampering)", {"report": v[1]}))
    hits = [g.decode("latin1") for g in GENERATORS if g in low]
    if hits:
        out.append(Finding("media.generator_metadata", "medium", "Metadata names an AI generator", {"strings": hits}))
    for clf in CLASSIFIERS:
        score, name = clf(data)
        if score >= 0.9:
            out.append(Finding("media.classifier", "medium", f"{name} scored {score:.2f}", {"score": score}))
    return out
